ProtonMail/design-system

- _sass/reusable-components/_design-system-util-typo-fix.scss
- helpers.html
Doing italic without using any tag.
- added `.italic` class
Example: https://design-system-beta.netlify.com/helpers/
Fixes #14
> Feat #14 - add italic class

- _sass/pm-styles/_pm-modal.scss
Centers the modal on all browsers
Fixes #3
> Fix #3 - alignment on Safari

- CHANGELOG
- helpers.html
- package.json
BECAUSE. DOCUMENTATION. ALWAYS. 
Fixes #23
> Fix #23 - documentation for `.unstyled` class

- CHANGELOG
- _sass/pm-styles/_pm-breadcrumb-domain.scss
- _sass/pm-styles/_pm-dropdown.scss
- _sass/pm-styles/_pm-forms.scss
- _sass/pm-styles/_pm-modal.scss
- _sass/reusable-components/_design-system-config.scss
- assets/css/styles-pm.scss
- how-to-use-design-system.html
- icons.html
- package.json
Issues for WebPack builds, and better reusability
- use relative path for images (for webpack)
- add documentation for variables
- add missing `!default` on variables of the design system partials
- updated `styles-pm` comments and “how to use design system” for variables
- indentation fixes
Fixes #36
> Feat #36 - update paths for images in CSS

- CHANGELOG
- _sass/reusable-components/_design-system-links-icons.scss
- icons.html
SVG 4 ever !!!! (works even on IE11)
Look at the doc here: https://design-system-beta.netlify.com/icons/#sizes-colors
Basically, we can do whatever we want.
Fixes #34
> Feat #34 - stroke width bigger for icons

- _layouts/default.html
- _sass/design-system-website/_global-structure.scss
- assets/js/main.js
Add gradient at the bottom of the navigation on the left when it is scrollable.
- This toggles a class `has-scroll-inside-navigation` on `js-sidebar-container`.
- When this class is activated, it adds a `::before` element on `progressBar-container` with adds the gradient on the top of previous element `nav`.
- this gradient is toggled when the user resizes his windows, when the page is loaded, and when there is a click on the expanding sections (with Mutation Observer). If the user scrolls to the end of this div, the gradient is removed.
Fixes #44
> Feat #44 - gradient for navigation scrolling

- _sass/pm-styles/_pm-forms.scss
- forms.html
- rely on `aria-invalid="true"` for redborder on input (better for a11y)
- linked via `aria-describedby` to error div
- transitionned to appear as softly as possible
http://recordit.co/IAr9GHHP2B
Fixes #81
> Feat #81 - error in forms

- forms.html
THOU SHALT DOCUMENT EVERYTHING.
- added example in doc.
Fixes #96
> Fix #96 - documentation for .pm-field--tiny

- _sass/pm-styles/_pm-buttons.scss
- buttons.html
Fix `pm-button--link` when used with `pm-button`
Fixes #97
> Fix #97 - mismatch for pm-button--link when used with pm-button

- CHANGELOG
- _sass/reusable-components/_design-system-layout-modules.scss
- helpers.html
We needed a helper to disable pointer-events.
- add `no-pointer-events` helper class
- documented
Fixes #108
> Feat #108 - no-pointer-events helper class

- _sass/pm-styles/_pm-buttons.scss
- _sass/pm-styles/_pm-dropdown.scss
- _sass/pm-styles/_pm-wizard.scss
- drop-down.html
- fixed bug on button group with 2 buttons `last/first-of-type`
- revamped drop down code (removed class, simplified, choosed classname more generic)
- also moved button classes to drop down and generalised `focus-within` 
- added group button example with colors
- fixed color management for caret
- updated leftArrow/rightArrow to modifier classes
Bonuses: 
- added modifier `wizard-container--noTextDisplayed` for wizard (hides the current step)
- fixed button--link modifier (background transparent
- documentation for drop down in button groups
Fixes #124
> Fix #124 - Group button with expand

- CHANGELOG
- _sass/pm-styles/_pm-dropdown.scss
This fixes several issues:
- if an element is alone in the drop down
- if the last one has to be hidden.
- updated selector
Fixes #185
> Fix #165 - dropDown-item border display

- _sass/pm-styles/_pm-containers.scss
Currently the row that's being re-ordered is being hidden by open modal. Applying same z-index as the modal fixes the issue.
Required for https://github.com/ProtonMail/proton-contacts/issues/27
> Visible orderable row when modal is open

- CHANGELOG
- _sass/pm-styles/_pm-buttons.scss
- buttons.html
- added `pm-button--noborder`
Fixes #168
> Feat #168 - add pm-button--noborder modifier

- _sass/react-styles/_pm-dropdown.scss
- _sass/reusable-components/_design-system-layout-modules.scss
* Adds ability for dropdown to have dynamic width.
* Adds .absolute helper that sets position of the element to `absolute`.
* Adds .centered-absolute helper that sets position of the element to `absolute` and centers it both vertically and horizontally.
* Adds .top-left helper, that positions absolute element in the top left of the container (useful for `close` icons)
* Adds .opacity-40 helper, as some elements in designs requires opacity of 40%.
Fixes https://github.com/ProtonMail/react-components/pull/193
> Support new Dropdown styling properties & add new helpers.

- _sass/pm-styles/_pm-buttons.scss
No idea what this `z-index` is for @nico3333fr but it's causing problems, with other elements that should be on top most of the time (section titles for instance)
Removed, or at least `z-index` should be low, like 1.
Fixes ProtonMail/protonvpn-settings#69
> Remove z-index from active group button

- _sass/pm-styles/_pm-layout.scss
Needed a helper to reset rounded corners.
- Added `.rounded0`, `.rounded0-left` and `rounded0-right` helpers.
Needed for https://github.com/ProtonMail/react-components/pull/254
> Added .rounded0 helpers

- _sass/pm-styles/_pm-containers.scss
- _sass/reusable-components/_design-system-layout-modules.scss
Sometimes it is useful to combine borders for some custom use cases in admin panel: bot+left+right.
maxWidth 50% is useful for two sections side by side.  
- additional border helpers for more granularity
- mw50 helper.
> Add more border and max width options

- _sass/design-system-website/_global-structure.scss
- _sass/pm-styles/_pm-conversations.scss
For the new responsive design in `contacts` (https://github.com/ProtonMail/proton-contacts/issues/225), we need new CSS classes
- add `main-area--noHeader` class
- add `main-area--withToolbar--noHeader` class
- add `items-column-list--mobile` class
> new css classes for responsive design in contacts

- _sass/design-system-website/_global-structure.scss
I think there were a few typos in the `main-area-withToolbar` class, like redundant definitions and extra unneeded definitions.
I did some checks in `contacts` and `settings` to see that the proposed changes do not break the layout, and it seems fine
> Fix main-area-withToolbar CSS class

- flexbox-helpers.html
In the "Flexbox helpers" section of the web, there was a mismatch between the html code proposed and the one displayed:
- Resolve the mismatch
> fix mismatch between html and what is displayed
