_includes/sub-nav.html
_sass/design-system-website/_inside-content.scss
icons.html

Documentation for CSS sprites.
It solves everything. 
Fixes #12

Feat #12 - documentation for CSS sprites

---

CHANGELOG
_sass/pm-styles/_pm-containers.scss
package.json

Fix #21 - padding fix

---

CHANGELOG
_sass/pm-styles/_pm-breadcrumb-domain.scss
assets/css/styles-pm.scss
assets/img/sprite-for-css-only.svg
containers.html
how-to-use-design-system.html
package.json

Added styles.
Breadcrumb styles are correctly vocalized btw. 
https://design-system-beta.netlify.com/containers/
Fixes #17

Feat #17 - domain breadcrumb styles

---

_sass/design-system-website/_global-structure.scss
_sass/reusable-components/_design-system-reset.scss

- Fixed overflow on Chrome.
- also "fixed" a iOS Safari bug
Fixes #26

Fix #26 - overflow on chrome

---

_sass/pm-styles/_pm-panels.scss
assets/css/styles-pm.scss
containers.html
how-to-use-design-system.html

- styles and doc have been added for information panels
Fixes #28

Feat #28 - information panels

---

_sass/pm-styles/_pm-table.scss
table.html

Fix alignments.
- fixed styles, demo is here: https://design-system-beta.netlify.com/table/ 
Fixes #29

Fix #29 - alignment of icons in table

---

_sass/pm-styles/_pm-forms.scss
forms.html
right-to-left.html

- inverted translations
- fixed component in RTL
Fixes #45

Fix #45 - invert toggle

---

CHANGELOG
_headers
_sass/design-system-website/_inside-content.scss
_sass/pm-styles/_pm-forms.scss
assets/img/shared/sprite-for-css-only.svg
assets/js/main.js
forms.html
icons.html

Feat #49 - input states

---

CHANGELOG
_sass/pm-styles/_pm-buttons.scss
buttons.html

button aliases are modifiers now `--` :)
Fixes #47

Feat #47 - button aliases are modifiers now

---

404.html
CHANGELOG
_includes/sub-nav.html
_layouts/default.html
_sass/design-system-website/_global-structure.scss
_sass/design-system-website/_inside-content.scss
_sass/design-system-website/_print.scss
_sass/design-system-website/_responsive.scss
_sass/design-system-website/_webfonts-hx.scss
_sass/reusable-components/_design-system-colors.scss
_sass/reusable-components/_design-system-config.scss
_sass/reusable-components/_design-system-layout-modules.scss
_sass/reusable-components/_design-system-links-icons.scss
_sass/reusable-components/_design-system-print.scss
assets/js/main.js
colors.html
helpers.html
how-to-use-design-system.html
icons.html
package.json
sass-variables.html

- put variables in `design-system-config`
- rewamped color pages
- add `h100` class
- added documentation page on Sass variables
- add missing color in icons
- fix 404 page
Fixes #60

Feat #60 - refactoring Sass variables

---

CHANGELOG
_sass/pm-styles/_pm-forms.scss
_sass/pm-styles/_pm-loadingcontent.scss
assets/js/main.js
forms.html

- add `aria-busy="true"` state to toggle
Fixes #54

Feat #54 - state "working/busy" on toggle

---

_sass/reusable-components/_design-system-layout-modules.scss
_sass/reusable-components/_design-system-responsive.scss

- reordered padding/margin helpers
Fixes #66

Fix #66 - reordered padding/margin helpers

---

_sass/reusable-components/_design-system-layout-modules.scss
conversations.html
helpers.html

Provides a class for something often used on actual v3
Fixes #70

Feat #70 - add scroll-smooth-touch class

---

_headers
_sass/design-system-website/_inside-content.scss
_sass/pm-styles/_pm-containers.scss
_sass/pm-styles/_pm-header-searchbar.scss
assets/img/shared/sprite-for-css-only.svg
containers.html
icons.html

Add styles for details/summary
https://design-system-beta.netlify.com/containers/
Fixes #69

Feat #69 - styles for details/summary

---

CHANGELOG
_includes/header.html
_sass/design-system-website/_responsive.scss

Fix responsive display
Fixes #73

Fix #73 - fix display top nav

---

forms.html

Feat #84 - warning message

---

_sass/pm-styles/_pm-forms.scss
forms.html

- set up max width for input/select/textarea
- fix select text overflow
- updated `ng-valid` to `is-valid` (byebye Angular)
- fix `pm-label` alignment
Fixes #88

Feat #88 - container for inputs

---

CHANGELOG
_sass/reusable-components/_design-system-reduced-motion.scss
assets/css/styles-pm.scss
forms.html
how-to-use-design-system.html

If a user has defined in his OS settings to reduce animations, the website will cancel all animations/transitions.
- create partial with this "reset".
Fixes #87

Feat #87 - prefers-reduced-motion: reduce MQ

---

CHANGELOG
_sass/pm-styles/_pm-buttons.scss
_sass/pm-styles/_pm-dropdown.scss
_sass/reusable-components/_design-system-layout-modules.scss
_sass/reusable-components/_design-system-links-icons.scss
buttons.html
drop-down.html
helpers.html

Drop down menus.
- added pagination drop down
- added button drop down
- added class `.increase-surface-click` class (needed for pagination drop down, and could be used for other cases, to increase tap zone)
- fixed documentation in group buttons
Fixes #91

Feat #91 - drop down menus

---

CHANGELOG
_sass/pm-styles/_pm-forms.scss
assets/js/main.js
forms.html
right-to-left.html

- added password revealer
- also checked in RTL
- added two reset for IE/EDGE about inputs
Fixes #71

Feat #71 - password revealer

---

CHANGELOG
_layouts/default.html
_sass/pm-styles/_pm-notifications.scss
_sass/reusable-components/_design-system-layout-modules.scss
assets/js/main.js
flexbox-helpers.html
notifications.html

Manage a list of notifications
- set up a container using flex
- set up animations
- bonus: added a flexbox helper
http://recordit.co/sOnbiRkNJV
Fixes #7

Feat #7 - list of notifications

---

_sass/pm-styles/_pm-modal.scss
assets/js/main.js
modals.html

Modals enhancements
- added scroll inside modal (requested by design)
- centering checked (ok on all major browsers)
- added shadows in case of long content (requested by design)
- added anim out
- Cleanup, positionning, RTL tests, comments 
Fixes #19

Fix #19 - modals

---

CHANGELOG
_sass/pm-styles/_pm-containers.scss
containers.html

-  added `border-bottom` helper class
Example here: https://design-system-beta.netlify.com/containers/
Fixes #109

Feat #109 - border bottom helper

---

_sass/pm-styles/_pm-modal.scss
_sass/pm-styles/_pm-notifications.scss
assets/js/main.js
modals.html
namespacing-classes.html

Inconsistencies in animation naming + missing conventions
Also missed some helpers/documentation
- Update notifications/modals after discussion with @mmso
- documentated in namespacing classes
- added mention of modifier convention
- documented modal modifier `pm-modal--inBackground` and animation names for modals
Fixes #117

Feat #117 updated/standardized animations and classnames

---

CHANGELOG
_sass/pm-styles/_pm-containers.scss
containers.html

- `shadow-container` class in https://design-system-beta.netlify.com/containers/
Fixes #118

Feat #118 container with shadow

---

CHANGELOG
_sass/reusable-components/_design-system-util-typo-fix.scss
helpers.html

- add capitalize helper
Fixes #127

Feat #127 - add capitalize helper

---

_sass/pm-styles/_pm-modal.scss
modals.html

- update all modal positionning
Fixes #123

Feat #123 - change positionning for multiple modals

---

CHANGELOG
_sass/pm-styles/_pm-containers.scss
containers.html

- added `block-info-success`/`block-info-standard-success` in containers
Fixes #133

Fix #133 - add block-info-success/block-info-standard-success classes

---

CHANGELOG
_sass/pm-styles/_pm-conversations.scss
conversations.html

- Updated fake checkbox in conversations (WIP)
Fixes #116

Feat #116 - fake checkboxes

---

CHANGELOG
_sass/reusable-components/_design-system-reset.scss
containers.html

- Reseted `figure` default browsers styles
- added an example in containers
Fixes #135

Feat #135 - CSS reset for figure tag

---

CHANGELOG
_layouts/default.html
_sass/design-system-website/_global-structure.scss
_sass/design-system-website/_responsive.scss
_sass/pm-styles/_pm-conversations.scss
_sass/reusable-components/_design-system-config.scss
sass-variables.html

Will be useful also for wider screen adaptations.
- added <code>--width-sidebar</code> and <code>--width-subnav</code> CSS variables
Fixes #143

Feat #143 - add 2 CSS variables

---

CHANGELOG
_sass/pm-styles/_pm-forms.scss
forms.html

- added `pm-field--highlight` modifier
- added example in the doc (with bold and align text)
Fixes #146

Feat #146 - add pm-field--highlight modifier

---

CHANGELOG
_sass/pm-styles/_pm-meterbar.scss
settings.html

- added designs for meter tag in settings
Fixes #138

Feat #138 - meter bar designs

---

CHANGELOG
_sass/design-system-website/_global-structure.scss
_sass/design-system-website/_responsive.scss
_sass/reusable-components/_design-system-reset.scss
sass-variables.html

- POC screen adaptation for very large screens (to test)
Fixes #142

Feat #142 - adaptations for very large screens

---

CHANGELOG
_sass/pm-styles/_pm-dropdown.scss
drop-down.html

- add class `dropDown-contentInner`
- fixed display (shadows, margins, etc.)
- added documentation about it
Fixes #141

Fix #141 - drop down max-height

---

CHANGELOG
_sass/design-system-website/_responsive.scss
_sass/reusable-components/_design-system-layout-modules.scss
helpers.html
icons.html

- renamed some classes for CSS multicolumns (consistency)
- renamed some Sass variables for better consistency
- added documentation about width helpers
Fixes #152

Feat #152 - documentation helper

---

CHANGELOG
_sass/pm-styles/_pm-conversations.scss
conversations.html

- updated classnames for conversation lists (for `item-`, more generic, as it is used in contacts)
Fixes #151

Feat #151 -  classnames for conversation lists

---

CHANGELOG
_includes/header.html
_sass/design-system-website/_webfonts-hx.scss
_sass/pm-styles/_pm-containers.scss
_sass/reusable-components/_design-system-layout-modules.scss
_sass/reusable-components/_design-system-util-typo-fix.scss
containers.html

- added dropdown logout :)
- added helpers `opacity-30`, `lh100`, `bordered` container
- commented some stuff (`q` styles)
Fixes #139

Feat #139 - log out expand menu

---

CHANGELOG
_sass/design-system-website/_exceptions.scss
_sass/design-system-website/_global-structure.scss
assets/css/styles-pm.scss

- fixed navigation padding (added partial `exceptions` ONLY for Design System website)
Fixes #158

Feat #158 - CSS for exceptions and fix navigation padding

---

CHANGELOG
_sass/pm-styles/_pm-cursors.scss
assets/css/styles-pm.scss
helpers.html
how-to-use-design-system.html

- added cursor helper classes (useful for some components/cases

Feat - cursor helper classes

---

_sass/reusable-components/_design-system-layout-modules.scss

- Need for some table column sizing
-
Fixes #

Add additional w15 class

---

_sass/pm-styles/_pm-tooltips.scss

Obsolete styles, see: https://github.com/ProtonMail/react-components/pull/143
-
-
Fixes #

Remove tooltip calculations, they are handled by js

---

_sass/pm-styles/_pm-containers.scss
containers.html

Add:
```scss
.dashed,
.dashed-container {
border: 1px dashed $pm-global-border;
}
.dashed-container {
border-radius: $global-border-radius;
}
```

Add dashed style for container

---

CHANGELOG
_sass/pm-styles/_pm-buttons.scss

- restricted active state only to button.
Video: https://recordit.co/uYw0I7P1d7

Fixed active state when applied to nested dropdowns

---

_sass/design-system-website/_global-structure.scss
assets/img/shared/generic-error.svg

Adding [this image](https://app.zeplin.io/project/5bb1deae290afc111d140a3f/screen/5d12fb8adfb0cd644f7ad0f0
) from Zeplin to the directory

Add image from Zeplin

---

_sass/react-styles/_pm-dropdown.scss
_sass/react-styles/_pm-tooltip.scss
package-lock.json

`left-bottom`, `left-top`, `right-top`, `right-bottom` placements for dropdowns and tooltips. Now all positions are covered.

Add missing four placements for tooltips and dropdowns

---

_sass/reusable-components/_design-system-colors.scss
_sass/reusable-components/_design-system-config.scss
colors.html

- Add new CSS class to handle new colors.
- Documentation updated.

Fix #196 - Add vpnbasic and vpnplus colors

---

assets/img/shared/unsupported-browser-settings.svg
assets/img/shared/unsupported-browser.svg

Add unsupported browser images

---

_sass/pm-styles/_pm-modal.scss

- Vertical centering with 3d transformations cause it to end up on uneven pixels which cause it to be blurry on certain browsers.
- Wrap in another container, and use vertical centering with flex.
Fixes #217
Note: This breaks the design system. Discussed with @nico3333fr that it's ok for now.

Position modals with flex instead of 3d transformations

---

_sass/pm-styles/_pm-buttons.scss

Adding a modifier needed for a single component of proton-contacts. See https://github.com/ProtonMail/proton-contacts/pull/153

whiteborder modifier for blue button

---

CHANGELOG
_sass/design-system-website/_global-structure.scss
_sass/pm-styles/_pm-aside.scss
_sass/pm-styles/_pm-navigation.scss
_sass/pm-styles/_pm-subnav.scss
_sass/pm-styles/_pm-toolbar.scss
assets/css/styles-pm.scss

- splitted `global-structure` into several fragments

Fix - add new fragments in Design System

---

_sass/pm-styles/_pm-conversations.scss
conversations.html

Implemented design but **on hold for visibility issues.**
- added states

WIP: Feat - hover state for conversations

---

CHANGELOG
_sass/pm-styles/_pm-conversations.scss
conversations.html

Fixes some issues on Mail react.
- revamped selectors
- moved colors to Design system
- fix example on design system website

Fix selected conversations

---

_sass/pm-styles/_pm-dark-theme.scss

For some reason the encoding of the darkmode.scc file was not correct. No changes to the content, just the file encoding

fix weird encoding of darkmode.scss

---

_sass/pc-styles/_pc-calendar-grid.scss

Add min-height to calendar daygrid

---

_sass/pm-styles/_pm-conversations.scss

Fix background color on https://github.com/ProtonMail/proton-contacts/issues/374

Set contact item background to white

---

_sass/pc-styles/_pc-calendar-grid.scss

Make part day event right margin consistent with all day event right margin

---

_sass/pc-styles/_pc-calendar-grid.scss
_sass/reusable-components/_design-system-math.scss

Improve outside modifier calculations
